---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lurkm.
--- DateTime: 29.06.2020 19:10
---

fx_version 'adamant'
game 'gta5'

ui_page 'ui/index.html'

files
{
    'ui/*',
    'ui/assets/*'
}

client_scripts{
    "client.lua",
}

server_scripts {
    "@vrp/lib/utils.lua",
    "server_vrp.lua"
}